# Generated by Django 4.1.3 on 2022-11-15 19:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="description",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
    ]
