# Generated by Django 4.1.3 on 2022-11-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_article_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="l'image de l'article"
            ),
        ),
    ]
